param($dataCenter, $cluster, $vmfolder, $dataStore, $standardPortGroup, [bool] $skipServerVerification=$True, $server, $username, $password )
Write-Host("Running smoke tests with params:")
Write-Host("    --datacenter:                   $dataCenter")
Write-Host("    --cluster:                      $cluster")
Write-Host("    --vmfolder:                     $vmfolder")
Write-Host("    --datastore:                    $cluster")
Write-Host("    --standardportgroup:            $standardPortGroup")
Write-Host("    --skip-server-verification:     $skipServerVerification")
Write-Host("    --server:                       $server")
Write-Host("    --username:                     $username")
Write-Host("    --password:                     $password")
Write-Host("")
Write-Host("")
Write-Host("")
Write-Host("Testing Create ...")
./create-vm/CreateBasicVM.exe --datacenter "$dataCenter" --cluster "$cluster" --vmfolder "$vmfolder" --datastore "$dataStore" --standardportgroup "$standardPortGroup" --server "$server" --username "$username" --password $password --skip-server-verification $skipServerVerification
Write-Host("")
Write-Host("")
Write-Host("Testing List ...")
./list-vms/ListVMs.exe --server "$server" --username "$username" --password $password --skip-server-verification $skipServerVerification